name: 'SSH & VNC to GitHub Actions'
author: 'Fangsongs'
description: 'Connect to GitHub Actions VM via SSH & VNC for interactive debugging'
inputs:
  mode:
    description: 'choose tmate or ngrok mode'
    required: false
    default: 'tmate'
runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/*.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/${{ inputs.mode }}2actions.sh
      shell: bash
branding:
  icon: 'terminal'
  color: 'gray-dark'
